version: "3.9" # optional since v1.27.0
services:
  # sql-server-db:
  #   image: "mcr.microsoft.com/mssql/server:2017-latest"
  #   container_name: sql-server-db
  #   ports:
  #    - "1432:1433"
    
  #   environment:
  #     SA_PASSWORD: "Password1!"
  #     ACCEPT_EULA: "Y"
    
  igc-irms-postgres:

    image: postgres

    restart: always

    ports:

      - "5433:5432"

    environment:

      POSTGRES_USER: "admin"

      POSTGRES_PASSWORD: "admin123"
      




  igniteconnex:
    image: igniteconnex.azurecr.io/runtime:3.0.5
    ports:
      - "1880:1880"
    environment:
      IGNITE_API_SECRET: 6f98e816f60f6747d813774c8d8e9c361964259a
      PROJECT_NAME: irmsintern
      CLIENT_ID: IRMS_PORTAL
      CLIENT_SECRET: USTtAQEqaFosFCZysbrS1y0stblFUYC4
      AUTH_SERVER_URL: https://sso.igniteconnex.io/auth
      APP_URL: http://localhost:1880
      START_MODE: PROJECT
      DB_SSL_OPTION: "false"


      DATABASE_URL: "postgres://admin:admin123@[igc-irms-postgres]:5432/postgres"
      # DATABASE_URL: "mssql://sa:Password1!@localhost:1432/tempdb"
    volumes:
      - ./data/ignite_flow:/usr/src/igniteconnex
    depends_on:
      - igc-irms-postgres
      # - sql-server-db
networks:
  default:
    external: true
    name: ignite
